language: python
python:
- 3.8
services:
- postgresql
install:
- psql -c 'create database django_db owner postgres;' -U postgres
- pip install -r requirements.txt
script:
- python manage.py migrate
- python manage.py test shop/tests/
deploy:
  provider: heroku
  api_key:
    secure: tY46z0qU/nPrEDbrjrZbFNXuB5h8ms9QRMMYlDgcF0XM1w8e8vDYj/muw3b9gNFbUlTZVtODKf3xLUULJOCkeLMLEph4yT6SafH12a9eh7GPdFX94zfAkv+vyYlE9eGOeBpKISEH6vVfXnn0UU6D5stTfA6ZrBecJEgv2yP34BvhsgVKmfskB/ll23IN1S4x0zJgUHZOgOm8by/W9W5BvNUVQduDPZEGB5Ju+cDPZiN3zTUGFXB2i0QrZYtRgKnumYpdF8gxS4+UZCYQSZ+jy8AuD0s/mtO9QbAfCZqc/g0Tni+C6/l5QGyg8EvOqQM2dQQnnDiHU5D/eqLsAFaHWvurzhsiXLm17e14pRQu0Tiz5O+bbNRKMAeGXONwLPHUgh+rmZNGacrAeNThMa8m5vVXkI1yTbZsHfjuOJ1/Lw3q8Z8jqkd6axQLOHbGtbLFRPkoaU2mKG9hM+KwoAdddwOt75JDJ12iBV6NYsBT1omcHLkdfSqN0Oz+QJ+0wIYJO67Y/Ypf/QEK3kiG74yQfxMiSU2fsq7R471X0dxBe9ZFDX13xVgJeKawn9/iEDsR952Ti4UKFn3J47ZgRvFt6xC0YO46/5+Dl9h1ZZBhUUf09I1sFAh2pvi/MRqd7fbDZcR0hf/kUB++8m46jfl7k1A6PDkvPjYthZdLGdJ8xUs=
  app: shopvsevo
  run: python manage.py loaddata products.yaml && python manage.py migrate
  on: master
