# Generated by Django 3.2.9 on 2021-12-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211203_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
